name: code_realm
description: An Android app that is a repo for bet codes.

version: 1.0.2+3

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.0.0
  provider: ^6.0.4
  firebase_auth: ^3.4.2
  firebase_core: ^1.10.6
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^12.0.4
  cupertino_icons: ^1.0.0
  http: ^0.13.1
  fluttertoast: ^8.0.8
  google_sign_in: ^5.2.1
  cloud_firestore: ^3.5.1
  introduction_screen: ^3.1.1
  shared_preferences: ^2.0.5
  new_version: ^0.3.1
  intl: ^0.17.0
  date_time_picker: "^2.0.0"
  scrollable_positioned_list: ^0.3.1
  flutter_background: ^1.1.0
  flutter_dotenv: ^5.0.2
  firebase_core_platform_interface: 4.5.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - file.env
    - assets/

