name: code_realm
description: An Android app that is a repo for bet codes.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^0.12.1+1
  provider: ^4.3.3
  firebase_auth: ^1.1.1
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.0.0
  cupertino_icons: ^1.0.0
  http: ^0.13.1
  fluttertoast: ^8.0.8
  google_sign_in: ^5.2.1
  cloud_firestore: ^1.0.6
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  date_time_picker: "^2.0.0"
  scrollable_positioned_list: ^0.2.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

